version: "3.9"

services:

  # postgresql service (database)
  pgdb:
    # set name for your container, if not random name will be assigned
    container_name: postgres-db
    # using pgsql version 15 alpine
    image: postgres:15-alpine
    # bind PC localhost:5432 to Docker localhost:5432
    ports: 
      - 5432:5432
    restart: unless-stopped
    # bind volume to docker 'pgdata' folder to avoid data loss on next run
    volumes:
      - pgdata:/var/lib/postgresql/data
    # load .env properties from docker.env file 'docker.env'
    env_file:
      - docker.env
    # connect to 'backend' docker network
    networks:
      - backend

  # pgadmin service (database client)
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    # bind PC localhost:8080 to Docker localhost:80, open browser http://localhost:8080
    ports:
      - 8080:80
    # bind volume to docker 'pgadmin' folder to avoid data loss on next run
    volumes:
      - pgadmin:/var/lib/pgadmin
    # load .env properties from docker.env file 'docker.env'
    # since .env properties are commonly shared between each services, use same key and file name
    env_file:
      - docker.env
    networks:
      - backend
    # wait for database to initialize then run
    depends_on:
      - pgdb

  # app service - this service depending on Dockefile set up
  app:
    container_name: dev-api
    # define location and name of Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile.DEV
    # port you expose or set for your app. Same as Dockerfile
    # bind PC localhost:3000 to Docker localhost:3000, open browser http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      # to enable JS hot reloading, it mount image '/var/www/app' working directory (defined in Dockerfile) with PC './app' directory
      - ./app:/var/www/app
      # to avoid nodemodules built in the image replace due to above, (./app has no node_modules!), move image node_modules to 'anynomous' folder
      - nodemodules:/var/www/app/node_modules
    env_file:
      - docker-dev.env
    restart: unless-stopped
    # command to execute when container run
    command: npm run start:dev
    networks:
      - backend
    depends_on:
      - pgdb

# Define / create a network
networks:
    # network name 'backend' use for services
    backend:
        # network name for Docker
        name: network-backend
        # 'bridge' type define an isolated localhost network inside 'this' Docker
        driver: bridge

# Define / create a Docker volume (folder)
volumes:
  # volume name 'pgdata' use for pgdb service
  pgdata:
    # volume name for Docker
    name: app-pgdata
  # volume name 'pgdata' use for pgadmin service
  pgadmin:
    name: app-pgadmin
  # volume name 'pgdata' use for app service
  nodemodules:
    name: app-nodemodules
